# Generated by Django 4.1.10 on 2023-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatroom_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="creator",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
