# Generated by Django 4.1.10 on 2023-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobo", "0005_answer_voter_question_voter_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
