# Generated by Django 4.1.10 on 2023-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobo", "0006_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="answer_images/"),
        ),
    ]
