# Generated by Django 4.1.10 on 2023-08-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroom_creator_alter_chatroom_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="description",
        ),
    ]
